<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\NewsletterApi\Model;

use Magento\Framework\DataObject;
use MagedIn\NewsletterApi\Api\Data\NewsletterSubscriptionInterface;

/**
 * Class NewsletterSubscription
 *
 * Newsletter subscription response data
 */
class NewsletterSubscription extends DataObject implements NewsletterSubscriptionInterface
{
    /**
     * @inheritdoc
     */
    public function setId(int $id)
    {
        $this->setData(self::SUBSCRIPTION_ID, $id);
        return $this;
    }

    /**
     * @inheritdoc
     */
    public function setEmail(string $email)
    {
        $this->setData(self::EMAIL, $email);
        return $this;
    }

    /**
     * @inheritdoc
     */
    public function setStatus($status)
    {
        $this->setData(self::STATUS, $status);
        return $this;
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->_getData(self::SUBSCRIPTION_ID);
    }

    /**
     * @inheritdoc
     */
    public function getEmail()
    {
        return $this->_getData(self::EMAIL);
    }

    /**
     * @inheritdoc
     */
    public function getStatus()
    {
        return $this->_getData(self::STATUS);
    }
}
