<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\NewsletterApi\Model;

use Magento\Framework\DataObject;
use MagedIn\NewsletterApi\Api\Data\NewsletterSubscriptionInterface;
use Magento\Newsletter\Model\Subscriber;

/**
 * Class NewsletterSubscription
 *
 * Newsletter subscription response data
 */
class NewsletterSubscription extends DataObject implements NewsletterSubscriptionInterface
{
    /**
     * @inheritdoc
     */
    public function setSubscriberId(int $subscriberId): self
    {
        $this->setData(self::SUBSCRIPTION_ID, $subscriberId);
        return $this;
    }

    /**
     * @inheritdoc
     */
    public function setEmail(string $email): self
    {
        $this->setData(self::EMAIL, $email);
        return $this;
    }

    /**
     * @inheritdoc
     */
    public function setStatus($status): self
    {
        $this->setData(self::STATUS, $status);
        return $this;
    }

    /**
     * @inheritdoc
     */
    public function getSubscriberId(): int
    {
        return $this->_getData(self::SUBSCRIPTION_ID);
    }

    /**
     * @inheritdoc
     */
    public function getEmail(): string
    {
        return $this->_getData(self::EMAIL);
    }

    /**
     * @inheritdoc
     */
    public function getStatus(): int
    {
        return (int) $this->_getData(self::STATUS);
    }

    /**
     * @inheritDoc
     */
    public function getStatusDescription(): string
    {
        switch ($this->getStatus()) {
            case Subscriber::STATUS_SUBSCRIBED:
                return 'subscribed';
            case Subscriber::STATUS_UNCONFIRMED:
                return 'unconfirmed';
            case Subscriber::STATUS_NOT_ACTIVE:
                return 'not_active';
            case Subscriber::STATUS_UNSUBSCRIBED:
                return 'unsubscribed';
            default:
                return 'unknown';
        }
    }
}
