<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

declare(strict_types=1);

namespace MagedIn\NewsletterApi\Model;

use MagedIn\NewsletterApi\Api\Data\OperationStatusInterface;
use Magento\Framework\DataObject;

/**
 * DocBlock for OperationStatus class.
 */
class OperationStatus extends DataObject implements OperationStatusInterface
{

    /**
     * @inheritDoc
     */
    public function setSuccess(bool $flag): self
    {
        return $this->setData(self::FIELD_SUCCESS, $flag);
    }

    /**
     * @inheritDoc
     */
    public function getSuccess(): bool
    {
        return (bool) $this->_getData(self::FIELD_SUCCESS);
    }

    /**
     * @inheritDoc
     */
    public function setMessage(string $message): self
    {
        return $this->setData(self::FIELD_MESSAGE, $message);
    }

    /**
     * @inheritDoc
     */
    public function getMessage(): string
    {
        return (string) $this->_getData(self::FIELD_MESSAGE);
    }
}
