<?php
/*
 *
 * McFadyen Digital
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  McFadyen
 * @package   McFadyen_NewsletterApi
 *
 * @copyright Copyright (c) 2021 McFadyen Digital.
 *
 * @author    Rojin R G <rrojin@mcfadyen.com>
 */

use Magento\Framework\Component\ComponentRegistrar;

ComponentRegistrar::register(
    ComponentRegistrar::MODULE,
    'McFadyen_NewsletterApi',
    __DIR__
);
