<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2021 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\NewsletterApi\Api\Data;

/**
 * Interface NewsletterSubscribeResponseInterface
 *
 * Newsletter subscribe response
 */
interface NewsletterSubscribeResponseInterface
{
    /**
     * Get success
     *
     * @return boolean
     */
    public function getSuccess();

    /**
     * Get message
     *
     * @return string|null
     */
    public function getMessage();
}
