<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2025 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\NewsletterApi\Api\Data;

/**
 * Interface NewsletterSubscriptionInterface
 *
 * Newsletter subscription response
 */
interface NewsletterSubscriptionInterface
{
    /**
     * Constants for keys of data array.
     */
    const SUBSCRIPTION_ID = 'subscription_id';
    const EMAIL = 'email';
    const STATUS = 'status';

    /**
     * Set ID
     *
     * set the internal id of the entity
     *
     * @param int $subscriberId
     * @return $this
     */
    public function setSubscriberId(int $subscriberId): self;

    /**
     * Set E-Mail Address
     *
     * set the e-mail address of the subscriber
     *
     * @param string $email
     * @return $this
     */
    public function setEmail(string $email): self;

    /**
     * Set status
     *
     * set the state of the subscription
     *
     * @param int
     *
     * @return $this
     */
    public function setStatus(int $status): self;

    /**
     * Get ID
     *
     * get the internal id of the subscription entity
     *
     * @return int
     */
    public function getSubscriberId(): int;

    /**
     * Get E-Mail Address
     *
     * get the email address of the subscriber
     *
     * @return string
     */
    public function getEmail(): string;

    /**
     * Get status
     *
     * get the status of the subscription
     *
     * @return int
     */
    public function getStatus(): int;

    /**
     * Get status
     *
     * get the status of the subscription
     *
     * @return string
     */
    public function getStatusDescription(): string;
}
