<?php
/*
 *
 * McFadyen Digital
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  McFadyen
 * @package   McFadyen_NewsletterApi
 *
 * @copyright Copyright (c) 2021 McFadyen Digital.
 *
 * @author    Rojin R G <rrojin@mcfadyen.com>
 */

namespace McFadyen\NewsletterApi\Api;

/**
 * Interface NewsletterManagementInterface
 *
 * Newsletter management for both customer and guest.
 */
interface NewsletterManagementInterface
{
    /**
     * Get Subscription information for a customer id
     *
     * @param int $customerId
     * @return \McFadyen\NewsletterApi\Api\Data\NewsletterSubscriptionInterface;
     */
    public function getSubscriptionForCustomer(int $customerId);

    /**
     * Subscribe a customer
     *
     * @param int $customerId
     * @return \McFadyen\NewsletterApi\Api\Data\NewsletterSubscribeResponseInterface;
     */
    public function subscribeCustomer(int $customerId);

    /**
     * Unsubscribe a customer
     *
     * @param int $customerId
     * @return \McFadyen\NewsletterApi\Api\Data\NewsletterSubscribeResponseInterface;
     */
    public function unsubscribeCustomer(int $customerId);

    /**
     * Subscribe a guest user with email
     *
     * @param string $email
     * @return \McFadyen\NewsletterApi\Api\Data\NewsletterSubscribeResponseInterface;
     */
    public function subscribe(string $email);
}
