<?php
/**
 * MagedIn Technology
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @category  MagedIn
 * @copyright Copyright (c) 2024 MagedIn Technology.
 *
 * @author    MagedIn Support <support@magedin.com>
 */

namespace MagedIn\NewsletterApi\Api;

use MagedIn\NewsletterApi\Api\Data\NewsletterSubscriptionInterface;
use MagedIn\NewsletterApi\Api\Data\OperationStatusInterface;

/**
 * Interface NewsletterManagementInterface
 *
 * Newsletter management for both customer and guest.
 */
interface NewsletterManagementInterface
{
    /**
     * Get Subscription information for a customer id
     *
     * @param int $customerId
     * @param int|null $storeId
     *
     * @return NewsletterSubscriptionInterface;
     */
    public function getSubscriptionByCustomerId(int $customerId, int $storeId = null): NewsletterSubscriptionInterface;

    /**
     * Subscribe a customer
     *
     * @param int $customerId
     * @param int|null $storeId
     *
     * @return OperationStatusInterface
     */
    public function subscribeByCustomerId(int $customerId, int $storeId = null): OperationStatusInterface;

    /**
     * Unsubscribe a customer
     *
     * @param int $customerId
     * @param int|null $storeId
     *
     * @return OperationStatusInterface ;
     */
    public function unsubscribeByCustomerId(int $customerId, int $storeId = null): OperationStatusInterface;

    /**
     * Subscribe a guest user with email
     *
     * @param string $email
     * @param int|null $storeId
     *
     * @return OperationStatusInterface ;
     */
    public function subscribeByCustomerEmail(string $email, int $storeId = null): OperationStatusInterface;

    /**
     * Unsubscribe a guest user with email
     *
     * @param string $email
     * @param int|null $storeId
     *
     * @return OperationStatusInterface ;
     */
    public function unsubscribeByCustomerEmail(string $email, int $storeId = null): OperationStatusInterface;
}
